import { Router } from 'express';
import rateLimit from 'express-rate-limit';
import { requireAuth, requireModule, requireRole } from '../middleware/auth.js';
import * as raw from '../controllers/student.controller.js';
import * as rawFees from '../controllers/fees.controller.js';
import * as rawLibrary from '../controllers/library.controller.js';
import * as rawOnline from '../controllers/onlinePayments.controller.js';
import * as rawAttendance from '../controllers/attendance.controller.js';
import * as rawExams from '../controllers/exams.controller.js';
import * as rawLearning from '../controllers/learning.controller.js';
import * as rawQuizzes from '../controllers/quiz.controller.js';
import { uuidParam, wrapAll } from './wrap.js';

const student = wrapAll(raw);
const fees = wrapAll(rawFees);
const library = wrapAll(rawLibrary);
const online = wrapAll(rawOnline);
const attendance = wrapAll(rawAttendance);
const exams = wrapAll(rawExams);
const learning = wrapAll(rawLearning);
const quizzes = wrapAll(rawQuizzes);
const router = Router();
// Each order is a call to Razorpay, so keep a stuck/abusive client from hammering it
const orderLimiter = rateLimit({ windowMs: 60_000, limit: () => Number(process.env.PAYMENT_ORDERS_PER_MINUTE) || 10, standardHeaders: true, legacyHeaders: false, message: { message: 'Too many payment attempts. Please wait a minute and try again.' } });
router.use(requireAuth, requireRole('student'));
router.param('id', uuidParam);

router.get('/dashboard', student.dashboard);
router.get('/profile', student.profile);
router.get('/institute', student.institute);
router.get('/calendar', requireModule('calendar'), student.calendar);
router.get('/timetable', requireModule('timetable'), student.timetable);
router.get('/attendance', requireModule('attendance'), attendance.myAttendance);
router.param('enrollmentId', uuidParam);
router.param('lessonId', uuidParam);
router.get('/learning', requireModule('learning'), learning.myLearning);
router.get('/learning/:enrollmentId', requireModule('learning'), learning.myEnrollment);
router.post('/learning/:enrollmentId/start', requireModule('learning'), learning.start);
router.put('/learning/:enrollmentId/lessons/:lessonId', requireModule('learning'), learning.setLesson);
router.post('/learning/:enrollmentId/submit', requireModule('learning'), learning.submit);
router.get('/quizzes', requireModule('quizzes'), quizzes.myQuizzes);
router.get('/internal-marks', requireModule('quizzes'), quizzes.myInternalMarks);
router.post('/quizzes/:id/start', requireModule('quizzes'), quizzes.start);
router.put('/quizzes/:id/answers', requireModule('quizzes'), quizzes.save);
router.post('/quizzes/:id/submit', requireModule('quizzes'), quizzes.submit);
router.get('/quizzes/:id/result', requireModule('quizzes'), quizzes.myResult);
router.get('/results', requireModule('exams'), exams.myResults);
router.get('/results/:id/report-card.pdf', requireModule('exams'), exams.myReportCard);
router.get('/id-card.pdf', requireModule('id_cards'), student.idCard);
router.get('/fees', requireModule('fees'), fees.myFees);
router.get('/fees/payments', requireModule('fees'), online.myPayments);
router.get('/fees/payments/:id/receipt.pdf', requireModule('fees'), fees.myReceipt);
router.get('/fees/online/config', requireModule('fees'), online.config);
router.post('/fees/online/orders', requireModule('fees'), orderLimiter, online.createOrder);
router.post('/fees/online/verify', requireModule('fees'), online.verify);
router.get('/library/books', requireModule('library'), library.catalogue);
router.get('/library/my-issues', requireModule('library'), library.myIssues);

export default router;
