/**
 * File byte storage. Swap this module for an S3-compatible one in production: the rest of the
 * app only uses put / get / remove. Keys are generated by us ("<tenantId>/<uuid>"), never from
 * user input, so a hostile filename can't escape the upload directory.
 */
import fs from 'node:fs/promises';
import path from 'node:path';
import { env } from '../config/env.js';

const resolveKey = (key) => {
  const full = path.resolve(env.UPLOAD_DIR, key);
  if (!full.startsWith(path.resolve(env.UPLOAD_DIR) + path.sep)) throw new Error('Invalid storage key');
  return full;
};

export async function put(key, buffer) {
  const full = resolveKey(key);
  await fs.mkdir(path.dirname(full), { recursive: true });
  await fs.writeFile(full, buffer, { flag: 'wx' });
}
export const get = (key) => fs.readFile(resolveKey(key));
export const remove = (key) => fs.rm(resolveKey(key), { force: true });
