/**
 * "I'm not a robot" check.
 *
 * Two providers live side by side. Which one runs is decided once, by
 * env.RECAPTCHA_ENABLED (true only when both RECAPTCHA_SITE_KEY and
 * RECAPTCHA_SECRET_KEY are set in server/.env):
 *
 *  - Google reCAPTCHA v2 (real widget, verified via verifyRecaptcha()).
 *  - The built-in custom check (behaviour signals + maths fallback), used
 *    automatically whenever no reCAPTCHA keys are configured.
 *
 * Either way, a pass results in the SAME thing: a short-lived, single-use
 * captcha token from issueCaptchaToken(). /auth/login only ever calls
 * consumeCaptchaToken(token) -> boolean, so it doesn't know or care which
 * provider produced it.
 */
import crypto from 'node:crypto';
import jwt from 'jsonwebtoken';
import { env } from '../config/env.js';

const RECAPTCHA_VERIFY_URL = 'https://www.google.com/recaptcha/api/siteverify';

/**
 * Verifies a Google reCAPTCHA v2 response token server-side. Google requires
 * this check to happen on the server (never trust a client-side "solved"
 * flag) using the SECRET key, which must never reach the browser.
 * Docs: https://developers.google.com/recaptcha/docs/verify
 */
export async function verifyRecaptcha(token, remoteip) {
  if (typeof token !== 'string' || !token) return { success: false, reason: 'missing-token' };
  try {
    const body = new URLSearchParams({ secret: env.RECAPTCHA_SECRET_KEY, response: token });
    if (remoteip) body.set('remoteip', remoteip);
    const res = await fetch(RECAPTCHA_VERIFY_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body,
    });
    const data = await res.json();
    // data looks like: { success: true, challenge_ts, hostname, 'error-codes': [...] }
    return { success: data.success === true, errors: data['error-codes'] || [] };
  } catch {
    return { success: false, reason: 'network-error' };
  }
}

const CHALLENGE_TTL_MS = 3 * 60 * 1000;
const MAX_CHALLENGE_TRIES = 3;

const challenges = new Map(); // id -> { answer, expires, tries }
const usedTokens = new Map(); // jti -> expiry (ms)

setInterval(() => {
  const now = Date.now();
  for (const [id, c] of challenges) if (c.expires < now) challenges.delete(id);
  for (const [jti, exp] of usedTokens) if (exp < now) usedTokens.delete(jti);
}, 60_000).unref();

export function looksHuman({ elapsedMs, interactions, trusted, website }) {
  if (website) return false; // honeypot field was filled in
  if (trusted !== true) return false; // click was generated by a script
  if (!Number.isFinite(elapsedMs) || elapsedMs < 1500) return false; // clicked too fast
  if (!Number.isFinite(interactions) || interactions < 2) return false; // no mouse / touch / keyboard activity
  return true;
}

export function issueCaptchaToken() {
  return jwt.sign({ typ: 'captcha' }, env.JWT_SECRET, { expiresIn: '2m', jwtid: crypto.randomUUID() });
}

/** Verifies a captcha token and burns it so it can only be used once. */
export function consumeCaptchaToken(token) {
  if (typeof token !== 'string' || !token) return false;
  try {
    const p = jwt.verify(token, env.JWT_SECRET);
    if (p.typ !== 'captcha' || !p.jti || usedTokens.has(p.jti)) return false;
    usedTokens.set(p.jti, p.exp * 1000);
    return true;
  } catch {
    return false;
  }
}

export function createChallenge() {
  const a = crypto.randomInt(3, 15);
  const b = crypto.randomInt(2, 10);
  const ops = [
    { sym: '+', fn: (x, y) => x + y },
    { sym: '-', fn: (x, y) => x - y },
    { sym: 'x', fn: (x, y) => x * y },
  ];
  const op = ops[crypto.randomInt(0, ops.length)];
  const [x, y] = op.sym === '-' && a < b ? [b, a] : [a, b];
  const id = crypto.randomUUID();
  challenges.set(id, { answer: op.fn(x, y), expires: Date.now() + CHALLENGE_TTL_MS, tries: 0 });
  return { id, prompt: `What is ${x} ${op.sym} ${y}?` };
}

export function answerChallenge(id, answer) {
  const c = challenges.get(id);
  if (!c || c.expires < Date.now()) return { ok: false, expired: true };
  c.tries += 1;
  if (Number(answer) === c.answer && String(answer).trim() !== '') {
    challenges.delete(id);
    return { ok: true };
  }
  if (c.tries >= MAX_CHALLENGE_TRIES) challenges.delete(id);
  return { ok: false, expired: c.tries >= MAX_CHALLENGE_TRIES };
}
